config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
	get '/team', to: 'static_pages#team'
  get '/welcome/:anything', to: 'static_pages#welcome'
  #get '/user/:id', to: 'static_pages#user'

  resources :gossips
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
    has_many :gossips, through: :users
    has_many :comments, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
    has_many :like_comments
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :gossip_tags
    has_many :tags, through: :gossip_tags
    has_many :comments
    has_many :like_comments, through: :comments
    has_many :like_gossips


    validates :content, presence: true, length: {in: 6..197}
    validates :title, presence: true, length: {in: 3..14}
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/like_comment.rb
class LikeComment < ApplicationRecord
    belongs_to :user
    belongs_to :comment
end

app/models/like_gossip.rb
class LikeGossip < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/models/recipient.rb
class Recipient < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossip_tags
    has_many :gossips, through: :gossip_tags
    has_many :comments, through: :gossips
    has_many :like_comments, through: :comments
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips
    has_many :comments
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "Recipient"
    has_many :like_comments
    has_many :like_gossips
    has_many :comments, through: :like_comments
    has_many :gossips, through: :like_gossips


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

    def index
        @gossips = Gossip.all
    end

    def show
        @gossip = Gossip.find(params[:id])
    end

    def new
        @gossips = Gossip.new
    end

    def create
        @gossips = Gossip.new(title: params[:title], content: params[:content], user_id: rand(1..10))
        if @gossips.save # essaie de sauvegarder en base gossip
            # si ça marche, il redirige vers la page d'index du site
            puts "GG well save"
            redirect_to gossips_path
          else
            # sinon, il render la view new (qui est celle sur laquelle on est déjà)
            puts "Try again"
            render "new"
        end
    end

    def update
        @gossips = Gossip.find(params[:id])
        gossip_user = @gossips.user

        if @gossip.update(gossip_params)
            redirect_to gossip_path
          else
            render :edit_gossip_path
        end
    end

    def destroy
        @gossips = Gossip.find(params[:id])
        gossip_user = @gossips.user
    
        if current_user == gossip_user
          @gossip.destroy
          redirect_to gossip_path
        else
          puts "Can't destroy bruh"
        end
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @gossips = Gossip.all
  end

  def index
  end
  
  def team
  end

  def contact
  end

  def welcome
    @name = params[:anything]
  end

  def gossip
    @gossip = Gossip.find(params[:id])
  end

  def user
    @user = User.find(params[:id])
    @city = City.find(@user.city_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end

    def show
        @users = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<div class="card create-gossip">
  <div class="card-header">
    <h2>Editing gossip</h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <%= form_for(@gossip) do |f| %>
          <%= f.text_field :title, class: 'form-control' %>
          <%= f.text_area :content, class: 'form-control' %>
          <%= f.submit %>
      <% end %>
    </blockquote>
  </div>
</div>

app/views/gossips/index.html.erb
<h1> Gossip created ! </h1>

<%= link_to "Create another one", new_gossip_path %><br>
<%= link_to "or go back to the Home Page", root_path %><hr>

app/views/gossips/new.html.erb
<% if @gossips.errors.any? %>
        <h2>Une erreur est survenue</h2>
        <ul>
            <% @gossips.errors.full_messages.each do |msg| %>
                <li><%= msg %> </li>
            <%end%>
        
        </ul>
    <%end%>

    <% if @gossips.save %>
      <div class="alert alert-success" role="alert">
      <p> Success!</p>
        </div>
        <% end %>
  
  
  
  
  
  <div class="card-header">
    <h2>Setting up the gossip</h2><hr>
  </div>

      <%= form_tag url_for(action: 'create'), method: "post" do %>
      <font size="+2">  <%= label_tag 'Gossip title' %></font><br/>
        <%= text_field_tag 'title' %>
        <br /> <br />

      <font size="+2">  <%= label_tag 'Gossip description' %></font><br/>
        <%= text_area_tag 'content' %>
        <br /> <br />

        <%= submit_tag "Submit your gossip" %>

      <% end %>

app/views/gossips/show.html.erb
<p> Name: <a href="/users/<%= @gossip.user.id %>"><%= @gossip.user.first_name %></a></p>
<p> Title: <%= @gossip.title %></p>
<p> Content: <%= @gossip.content %></p>
<p> Created: <%= @gossip.created_at %></p>
<p> Updated: <%= @gossip.updated_at %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <style>
     @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap');
     body {
    background: linear-gradient(90deg, #FEE140 0%, #FA709A 100%);
    background-size: 400vh 400vh;
    animation: gradient 35s ease infinite;
    font-family: Roboto;
}

     @keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
    50% {
        background-position: 100% 50%;
    }
    100% {
        background-position: 0% 50%;
    }
}
    </style>
  </head>


<header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/">The Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/">Gossips <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/team">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact">Contact</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<center><h1> WELCOME BROS & BROSETTES ! </h1></center></br>

<%= link_to "Clic here to create your damn gossip bro", new_gossip_path %></br></br>
<%= link_to "Clic here to create your damn gossip bro", new_gossip_path %><hr>


<% @gossips.each do |x| %>
<p> Name: <%= x.user.first_name %><br>
    Title: <%= x.title %><br>
<a href="/gossips/<%=x.id%>" >Voir le gossip</a></p>
<% end %>

app/views/static_pages/team.html.erb
<h1>StaticPages#team</h1>
<p>Find me in app/views/static_pages/team.html.erb</p>

app/views/static_pages/welcome.html.erb
<h1> BIENVENUE <%= @name %>!</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>

app/views/users/show.html.erb
<p> Name : <%=@users.first_name%></p>
<p> Last Name : <%=@users.last_name%></p>
<p> Description : <%=@users.description%></p>
<p> Email : <%=@users.email%></p>
<p> Age : <%=@users.age%></p>
<p> City : <%=@users.city.name%></p>